### ISSUE TITLE
两个主要问题

### ISSUE THREAD

**Issue by alloai** [geekan/scrapy-examples#14]
目前有两个主要的问题，导致没法在scrapy 1.3 和python 3.5环境里面使用

1). 需要把`from urlparse import urlparse `改为`from urllib.parse import urlparse`
2).需要在所有的print 后面加括号
`print e` to `print (e)`

**Comment by XetRAHF** [comment]
可以使用以下方式检测python版本:
`import sys`
`if sys.version_info[0] < 3:`
`    raise "Must be using Python 3"`

**Comment by ingenika** [comment]
all done
