### ISSUE TITLE
请问你的模板是怎么继承的？

### ISSUE THREAD

**Issue by czly** [geekan/scrapy-examples#8]
template模板并没有在scrapy默认继承模板里呀
![qq 20160407100808](https://cloud.githubusercontent.com/assets/17497420/14338289/6319da4e-fca8-11e5-8a05-499d76f1d990.jpg)
![qq 20160407100903](https://cloud.githubusercontent.com/assets/17497420/14338296/6e20b2a0-fca8-11e5-84a3-3ff552e848dd.jpg)

**Comment by geekan** [comment]
现在要用startproject.sh来生成新项目
